//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdDinner.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinner
    {
        public Dinner()
        {
            this.RSVPs = new HashSet<RSVP>();
        }
    
        public int DinnerID { get; set; }
        public string Title { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Description { get; set; }
        public string HostedBy { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    
        public virtual ICollection<RSVP> RSVPs { get; set; }
    }
}
